const Roles = {
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  WRITER: "WRITER",
  CLERK: "CLERK",
  CUSTOMER: "CUSTOMER",
};

const VERIFY_CODE_TYPES = {
  VALIDATE_EMAIL: "VALIDATE_EMAIL",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
};

const MEMBER_STATUS = {
  PENDING: "PENDING",
  ACTIVATE: "ACTIVATE",
  DEACTIVATE: "DEACTIVATE",
  SUSPENDED: "SUSPENDED",
};

const DOC_STATUS = {
  EDITING: "EDITING",
  PENDING: "PENDING",
  WCHECKING: "WRITERCHECKING",
  WCONFIRM: "WRITERCONFIRM",
  CCHECKING: "CLERKCHECKING",
  CCONFIRM: "CLERKCONFIRM",
  COMPLETED: "COMPLETED",
};

module.exports = {
  Roles,
  VERIFY_CODE_TYPES,
  MEMBER_STATUS,
  DOC_STATUS,
};
